import { brand, ink } from "./index.ts";

/**
 * The Tailwind `@theme` partial, as a string.
 *
 * Kept apart from the script that writes it so the test can compare what the
 * generator *would* emit against what is on disk without shelling out or
 * touching the filesystem.
 *
 * Colours only. `globals.css` still declares radius, motion and the surface
 * variables by hand — the header of `./index.ts` says why, and `tokens.test.ts`
 * checks the ones this file leaves behind.
 */

const BANNER = `/*
 * Generated by @sailo/tokens. Do not edit.
 *
 * Change a value in packages/tokens/src/index.ts and run
 *   pnpm --filter @sailo/tokens generate
 * The test suite fails if this file and that one disagree, so a stale copy
 * cannot reach main.
 *
 * The prose explaining *why* these ramps are what they are lives in
 * globals.css, next to the import that pulls this in.
 */`;

function ramp(prefix: string, steps: Record<string, string>): string {
  return Object.entries(steps)
    .map(([step, value]) => `  --color-${prefix}-${step}: ${value};`)
    .join("\n");
}

export function themeCss(): string {
  return `${BANNER}

@theme {
${ramp("ink", ink)}

${ramp("brand", brand)}
}
`;
}
